  $ astral-convertor 01-builtins.smt2 --to s2s
  // Generated by Astral (https://github.com/TDacik/Astral)
  // expected status: sat
  
  // sort (Loc Loc)
  
  ddata LS_t {
    LS_t field_next;
  }.
  
  // heap sort ((Loc Loc) -> LS_t := c_ls(field_next))
  
  pred ls< x_1:LS_t,x_2:LS_t > ==
    emp & x_1=x_2
    or (exists e_2 : x_1::LS_t<e_2> * ls(e_2, x_2) & x_1=x_2).
  
  // variable x : (Loc Loc)
  // variable y : (Loc Loc)
  // variable z : (Loc Loc)
  
  checkent ls(x, y) * y::LS_t<x> & x=nil & y=nil & y=nil |- ls(y, x) * x::LS_t<y> & y=z & x=z & x=y.
