  $ astral-convertor 01-builtins.smt2 --to s2s
  // Generated by Astral (https://github.com/TDacik/Astral)
  // expected status: sat
  
  // sort (Loc Loc)
  
  ddata LS_t {
    LS_t field_next;
  }.
  
  // heap sort ((Loc Loc) -> LS_t := c_ls(field_next))
  
  pred ls< x_1:LS_t,x_2:LS_t > ==
    emp & x_1=x_2
    or (exists e_2 : ls(e_2, x_2) * x_1::LS_t<e_2> & x_1!=x_2).
  
  // variable x : (Loc Loc)
  // variable y : (Loc Loc)
  // variable z : (Loc Loc)
  
  checkent y::LS_t<x> * ls(x, y) & y!=null & x=null |- x::LS_t<y> * ls(y, x) & y!=z & x!=z & x!=y.

  $ astral-convertor 02-user_defined.smt2 --to s2s
  // Generated by Astral (https://github.com/TDacik/Astral)
  // expected status: unsat
  
  // sort (Loc Ref_TREE)
  
  ddata TREE {
    TREE left;
    TREE right;
  }.
  
  // heap sort ((Loc Ref_TREE) -> TREE := c_TREE(left, right))
  
  pred tree< x:TREE,h1:TREE > ==
    emp & x=h1
    or (exists r_1, l_1 : tree(r_1, null) * tree(l_1, h1) * x::TREE<l_1, r_1> & x!=h1)
    or (exists r_2, l_2 : tree(r_2, h1) * tree(l_2, null) * x::TREE<l_2, r_2> & x!=h1).
  
  // variable h : (Loc Ref_TREE)
  // variable x : (Loc Ref_TREE)
  
  checkent tree(h, null) * tree(x, h) & true |- tree(x, null) & true.

  $ astral-convertor 03-user_defined_imprecise.smt2 --pure-imprecise --to s2s
  // Generated by Astral (https://github.com/TDacik/Astral)
  // expected status: unsat
  
  // sort (Loc Ref_TREE)
  
  ddata TREE {
    TREE left;
    TREE right;
  }.
  
  // heap sort ((Loc Ref_TREE) -> TREE := c_TREE(left, right))
  
  pred tree< x:TREE,h1:TREE > ==
    emp & x=h1
    or (exists r_1, l_1 : x::TREE<l_1, r_1> * tree(l_1, h1) * tree(r_1, null) & x!=h1)
    or (exists r_2, l_2 : x::TREE<l_2, r_2> * tree(l_2, null) * tree(r_2, h1) & x!=h1).
  
  // variable h : (Loc Ref_TREE)
  // variable x : (Loc Ref_TREE)
  
  checkent tree(x, h) * tree(h, null) & true |- tree(x, null) & true.
