  $ astral-convertor 01-builtins.smt2 --to songbird
  // Generated by Astral (https://github.com/TDacik/Astral)
  // expected status: sat
  
  // sort (Loc Loc)
  
  data LS_t {
    LS_t field_next;
  };
  
  // heap sort ((Loc Loc) -> LS_t := c_ls(field_next))
  
  pred ls(x_1,x_2) :=
    emp & x_1=x_2
    \/ (exists e_2 . ls(e_2, x_2) * x_1->LS_t{e_2} & x_1=x_2);
  
  // variable x : (Loc Loc)
  // variable y : (Loc Loc)
  // variable z : (Loc Loc)
  
  checkentail y->LS_t{x} * ls(x, y) & y=nil & x=nil & x=nil |- x->LS_t{y} * ls(y, x) & y=z & x=z & x=y.
