open Convertor_sig

module Input = ParserContext
open Input

module Make (Convertor : CONVERTOR_BASE) = struct

  module C = Convertor

  let get_predicates (ctx : Context.t) =
    ctx.inductive_preds
    |> List.map SID.get_definition
    |> List.map (fun id ->
         if C.params.precise_semantics then id
         else PredicatePreprocessing.preprocess_cases PreciseToImprecise.to_imprecise id
       )

  let (++) x y = x ^ "\n" ^ y
  let (+++) x y = x ^ "\n\n" ^ y

  let lst fn xs = String.concat "\n" @@ List.map fn xs

  let convert (input : Context.t) =
    C.init input;
    C.comment "Generated by Astral (https://github.com/TDacik/Astral)"
    ++ C.set_status input.expected_status
    +++ (lst C.declare_sort @@ BatList.unique_cmp ~cmp:Sort.compare input.sorts) (* TODO: handle aliases elsewhere? *)
    +++ (lst C.declare_struct input.defs)
    +++ C.declare_heap_sort input.heap_sort
    +++ (lst C.declare_predicate @@ get_predicates input)
    +++ (lst C.declare_var input.vars)
    +++ C.add_check_sat input.phi
    ++ ""

  let store content path =
    let filename = Str.global_replace (Str.regexp "\\.smt2") C.params.suffix path in
    let channel = open_out_gen [Open_creat; Open_wronly] 0o666 filename in
    Printf.fprintf channel "%s" content;
    close_out channel

  let convert_and_store input = convert input |> store

  include Convertor

end
