open Convertor_sig

module Input = ParserContext
open Input

module Make (C : CONVERTOR_BASE) = struct
module Instantiate (O : OPTIONS) = struct

  let to_precise = C.params.precise_semantics && (not O.precise)
  let to_imprecise = (not C.params.precise_semantics && O.precise)

  let preprocess phi =
    NegationNormalisation.apply phi
    |> (fun phi -> if not C.params.supports_variadic_ops then RemoveVariadic.apply phi else phi)
    (*|> (fun phi -> if to_precise then PreciseToImprecise.to_precise phi else phi)*)
    |> (fun phi -> if to_imprecise then PreciseToImprecise.to_imprecise phi else phi)

  (** Preprocessing of inductive definitions is performed here to do treat
      built-in and used-defined predicates uniformly. *)
  let get_predicates (ctx : Context.t) =
    ctx.inductive_preds
    |> List.map GlobalSID.find
    |> List.map SID.ID.to_def
    |> List.map (fun id -> PredicatePreprocessing.preprocess_cases preprocess id)

  let (++) x y = x ^ "\n" ^ y
  let (+++) x y = x ^ "\n\n" ^ y

  let lst fn xs = String.concat "\n" @@ List.map fn xs

  let convert (input : Context.t) =
    let input = {input with phi = preprocess input.phi} in
    C.init input;
    C.comment "Generated by Astral (https://github.com/TDacik/Astral)"
    ++ C.set_status input.expected_status
    +++ (lst C.declare_sort @@ BatList.unique_cmp ~cmp:Sort.compare input.sorts) (* TODO: handle aliases elsewhere? *)
    +++ (lst C.declare_struct input.defs)
    +++ C.declare_heap_sort input.heap_sort
    +++ (lst C.declare_predicate @@ get_predicates input)
    +++ (lst C.declare_var input.vars)
    +++ C.add_check_sat input.phi
    ++ ""

  let store content path =
    let filename = Str.global_replace (Str.regexp "\\.smt2") C.params.suffix path in
    let channel = open_out_gen [Open_creat; Open_wronly] 0o666 filename in
    Printf.fprintf channel "%s" content;
    close_out channel

  let convert_and_store input = convert input |> store

  include C

end
end
