(library
  (name astral)
  (public_name astral)

  (libraries
    dolmen
    batteries
    ocamlgraph
    yojson
    ppx_deriving
    sexplib

    astral_cmd

    (select Z3_backend.ml from
       (z3 -> Z3_backend.real.ml)
       (-> Z3_backend.dummy.ml)
    )

    (select BitwuzlaNative.ml from
       (bitwuzla-cxx -> BitwuzlaNative.real.ml)
       (-> BitwuzlaNative.dummy.ml)
    )

    (select CVC5_native.ml from
       (cvc5 -> CVC5_native.real.ml)
       (-> CVC5_native.dummy.ml)
    )
  )

  (preprocess
    (pps ppx_compare ppx_deriving.enum ppx_deriving.show)
  )

  (modules_without_implementation
    datatype_sig
    logic_sig
    SMT_sig
    backend_sig
    translation_sig
    debug_sig
    logger_sig
    SetEncoding_sig
    location_sig
    encoding_context_sig
    HeapEncoding_sig
    ID_sig

    ParserContext_type
  )
)

(include_subdirs unqualified)

(documentation (package astral))

; Workaround for dune bug with alternative dependencies:
; https://github.com/ocaml/dune/issues/4383
(copy_files backend/*.ml)
(copy_files backend/*.mli)
