# Install dependencies & build Astral
#
# TODO: caching using actions/cache
#
# Author: Tomas Dacik (idacik@fit.vut.cz), 2024

name: Install dependencies and build Astral

on:
  workflow-call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2

      - name: Install dependencies
        run: opam install -y --deps-only --with-tests --with-doc .

      - name: Install Astral
        run: opam exec -- dune build
