# Workflow for running tests
#
# Author: Tomas Dacik (idacik@fit.vut.cz), 2022

name: Run tests

on: [push, pull_request]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
          dune-cache: true

      - name: Install dependencies
        run: opam install -y --deps-only --with-test .

      - name: Install bitwuzla
        run: opam install bitwuzla

      - name: Install Astral
        run: opam exec -- dune build

      - name: List backend configuration
        run: astral --backend-help

      - name: Run unit tests
        run: opam exec -- dune runtest

  regression-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
          dune-cache: true

      - name: Install dependencies
        run: opam install -y --deps-only --with-test .

      - name: Install bitwuzla
        run: opam install bitwuzla

      - name: Install Astral
        run: opam exec -- dune build

      - name: Run regression tests
        run: python3 scripts/run_tests.py

  deploy-doc:
    runs-on: ubuntu-latest

    # Avoid publishing PR branches
    if: github.event_name == 'push'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
          dune-cache: true

      - name: Install dependencies
        run: opam install -y --deps-only --with-test --with-doc .

      - name: Install bitwuzla
        run: opam install bitwuzla

      - name: Build documentation
        run: opam exec -- dune build @doc

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/default/_doc/_html
          destination_dir: branches/${{ github.ref_name }}
          keep_files: true

      - name: Deploy root index
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/pages
          destination_dir: .
          keep_files: true
