# Workflow for deploying docs
#
# Inspired by: https://github.com/ocaml/setup-ocaml/blob/master/EXAMPLES.md
#
# Author: Tomas Dacik (idacik@fit.vut.cz), 2024

name: Deploy documentation to GitHub pages

on:
  push:
    branches: [main, dev]

permissions: read-all

concurrency:
  group: deploy-odoc
  cancel-in-progress: true

jobs:
  deploy-odoc: Deploy

  environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

  permissions:
    contents: read
    id-token: write
    pages: write

  runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.2

    - name: Install dependencies
      run: opam install odoc

    - name: Build documentation
      run: opam exec -- dune build @doc

    - name: Set-up Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _build/default/_doc/_html

    - name: Deploy odoc to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
