# Reusable workflow to setup and build Astral
#
# Author: Tomas Dacik (idacik@fit.vut.cz), 2025

on:
  workflow_call:
    inputs: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.2
          dunecache: true

      - name: Install dependencies
        run: opam install -y --deps-only --with-test --with-doc .

      - name: Install Astral
        run: opam exec -- dune build
