name: Run tests

on: [push, pull_request]

jobs:

  setup:
    uses: ./.github/workflows/setup.yml

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: opam exec -- dune runtest
